# -*- coding: utf-8 -*-
"""Soczyste rabaty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU5lwdNa2GOPWmQ9-URaf30VnlBzQC0
"""

#importowanie potrzebnych bibliotek
import os
import openpyxl
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
from urllib.request import urlopen
import json
import io
import datetime



st.set_page_config(page_title='Łączenie danych do kalendarza', layout='wide')



tabs_font_css = """
<style>
div[class*="stTextInput"] label {
  font-size: 26px;
  color: black;
}
div[class*="stSelectbox"] label {
  font-size: 26px;
  color: black;
}
</style>
"""

st.title("Automat ŁĄCZENIE DANYCH DO KALENDARZA")


df_s = st.file_uploader(
    label = "Wrzuć plik RaportPromocyjny - stary"
)
if df_s:
    df_s = pd.read_csv(df_s, sep=';')
    st.write(df_s.head())

# Wybieranie tylko określonych kolumn z DataFrame
kolumny = [
    'Nazwa Promocji', 'Rabat Promocyjny',	'Rabat kwotowy',	'Id Materiału',	'Nazwa Materiału', 'Nazwa producenta sprzedażowego',	'identyfikator promocji',	'Data obowiązywania promocji od',	
    'Data obowiązywania promocji do',	'Ilość Klientów',	'Master ID'
]

#print("Typ df:", type(df))
# Filtruj kolumny w DataFrame
df_s = df_s[kolumny]

master_ids = [
    91, 89, 50, 49, 351, 64, 303, 320, 322, 357,
    257, 321, 78, 355, 203, 323, 340, 338, 253,
    356, 84, 87, 319, 344, 353, 331, 102, 224, 97,
    98, 352, 330, 333, 346, 212, 213, 211, 217,
    295, 342, 216, 215, 245
]

# Filtrowanie df_s
df_s = df_s[df_s['Master ID'].isin(master_ids)]


# Pobranie dzisiejszej daty w formacie YYYY-MM-DD
today = datetime.datetime.today().strftime('%d-%m-%Y')

# Tworzenie pliku Excel w pamięci
excel_file1 = io.BytesIO()

with pd.ExcelWriter(excel_file1, engine='xlsxwriter') as writer:
    # Zapisywanie arkuszy
    df_s.to_excel(writer, index=False, sheet_name='dane')

# Resetowanie wskaźnika do początku pliku
excel_file1.seek(0)

# Pobranie pliku w Streamlit
st.download_button(
    label='Pobierz dane do kalendarza',
    data=excel_file1,
    file_name=f'Dane_kalendarz_{today}.xlsx',
    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
)


